### ISSUE TITLE
Light don't Change...

### ISSUE THREAD

**Issue by Paullux** [MatthewMawby/RaveForm#1]
Hello, The Lights didn't change and i have an error.

```
TypeError: Cannot read property 'length' of undefined
    at setLights (/home/paul/RaveForm/server.js:100:28)
    at /home/paul/RaveForm/server.js:143:9
    at Layer.handle [as handle_request] (/home/paul/RaveForm/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/paul/RaveForm/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/paul/RaveForm/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/paul/RaveForm/node_modules/express/lib/router/layer.js:95:5)
    at /home/paul/RaveForm/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/paul/RaveForm/node_modules/express/lib/router/index.js:335:12)
    at next (/home/paul/RaveForm/node_modules/express/lib/router/index.js:275:10)
    at cookieParser (/home/paul/RaveForm/node_modules/cookie-parser/index.js:71:5)
```

**Comment by jdubz666** [comment]
Go into the node files listed and install any packages you don’t have.

Eg. you’ll need “npm i cookie-parser”... express, and a few more.

Good luck, I just got mine working.

**Comment by Spacefish** [comment]
Hey just figured this out :
You need to have rooms / or groups called "highs" and "lows" or change it on line 47 of server.js
