### ISSUE TITLE
npm cannot start: hue.upnpSearch is not a function

### ISSUE THREAD

**Issue by jianxizg** [MatthewMawby/RaveForm#4]
```$ npm start```

Then

```
> raveform@1.0.0 start
> node server.js

/home/leo/RaveForm/server.js:27
hue.upnpSearch().then(setHost).done();
    ^

TypeError: hue.upnpSearch is not a function
    at Object.<anonymous> (/home/leo/RaveForm/server.js:27:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code 1
npm ERR! path /home/leo/RaveForm
npm ERR! command failed
npm ERR! command sh -c node server.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-02T00_54_04_487Z-debug.log
```

**Comment by johnneerdael** [comment]
Same error seems this is no longer supported

**Comment by jawednur** [comment]
Got it up for me 
https://github.com/jawednur/RaveForm
